ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'


urlpatterns = [
    path('addtocart/<int:p>',views.addtocart,name="addtocart"),
    path('cartview/',views.cart_view,name="cartview"),
    path('cartremove/<int:p>',views.cartremove,name="cartremove"),
    path('full_remove/<int:p>', views.full_remove, name="full_remove"),
    path('order_form/',views.order_form,name="orderform"),
    path('orderview/',views.orderview,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views
app_name="search"

urlpatterns = [
    path('searchproducts/',views.searchproducts,name="searchproducts"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('allcategories/',views.allcategories,name="allcategories"),
    path('products/<int:p>',views.allproducts,name='products'),
    path('detail/<int:p>',views.detail,name='detail'),
    path('reg/', views.reg, name='register'),
    path('login/', views.userlogin, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('',views.home,name='home'),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price

    def __str__(self):
        return self.product.name

class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_item=models.IntegerField()
    phone=models.IntegerField(default=0)
    address=models.TextField()
    ordered_date = models.DateTimeField(auto_now_add=True)
    order_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")

    def __str__(self):
        return self.user.username

class Account(models.Model):
    acctnum=models.BigIntegerField()
    acctype=models.CharField(max_length=20)
    amount=models.IntegerField()

    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to='image',null=True,blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField()
    image = models.ImageField(upload_to='products', null=True, blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render
from cart.models import Cart,Order,Account
from shop.models import Product
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

@login_required
def cart_view(request):
    u=request.user
    total=0
    cart=Cart.objects.filter(user=u)
    for i in cart:
        total=total+i.quantity*i.product.price
    return render(request,'cart.html',{'cart':cart,'total':total})

@login_required
def addtocart(request,p):
    p=Product.objects.get(id=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock>0):
            cart.quantity+=1
            cart.save()
            p.stock-=1
            p.save()
    except:
        if(p.stock>0):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock -= 1
            p.save()

    return cart_view(request)

def cartremove(request,p):
    p = Product.objects.get(id=p)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (cart.quantity > 1):
            cart.quantity -= 1
            cart.save()
            p.stock += 1
            p.save()
        else:
             cart.delete()
             p.stock += 1
             p.save()
    except:
        pass
    return cart_view(request)

def full_remove(request,p):
    p = Product.objects.get(id=p)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        cart.delete()
        p.stock += cart.quantity
        p.save()
    except:
        pass
    return cart_view(request)

@login_required
def order_form(request):
    if(request.method=="POST"):
        address=request.POST['ad']
        p = request.POST['ph']
        n= request.POST['n']

        u = request.user
        c=Cart.objects.filter(user=u)

        total=0
        for i in c:
            total=total+i.quantity*i.product.price

        try:
            ac=Account.objects.get(acctnum=n)

            if(ac.amount>=total):
                print(ac.amount)

                ac.amount=ac.amount-total
                print(ac.amount)

                ac.save()
                for i in c:
                    o=Order.objects.create(user=u,product=i.product,address=address,phone=p,no_of_item=i.quantity,order_status="paid")
                    o.save()

                c.delete()
                msg="Order Placed Successfully"
                return render(request,'orderdetail.html',{'message':msg})
            else:
                msg="Insufficient Balance"
                return render(request, 'orderdetail.html', {'message': msg})
        except:
            pass

    return render(request,'orderform.html')

def orderview(request):
    u=request.user.id
    cart=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'cart':cart})

# Create your views here.

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q



def searchproducts(request):
    p=None
    q=""
    if(request.method=="POST"):
        query=request.POST['q']
        if(query):
            p=Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))
    return render(request,'searchproducts.html',{'p':p,'q':q})
# Create your views here.

ecommerce/shop/views.py
from django.shortcuts import (render,redirect)
from django.http import HttpResponse
from shop.models import Category,Product
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})
# Create your views here.

def allproducts(request,p):
    c=Category.objects.get(id=p)
    p=Product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})

def detail(request,p):
    p = Product.objects.get(id=p)
    return render(request,'detail.html',{'p':p})

def reg(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p= request.POST['p']
        c = request.POST['c']
        e = request.POST['e']

        if(c==p):
            u=User.objects.create_user(username=u,password=p,email=e,)
            u.save()
            return redirect('shop:allcategories')
        else:
            return HttpResponse("passwords are not same")
    return render(request,'register.html')



def userlogin(request):
    if (request.method=="POST"):
        u = request.POST['u']
        p = request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('shop:allcategories')
        else:
            return HttpResponse("invalid")
    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return userlogin(request)

def home(request):
    return render(request,'home.html')

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bungee&family=Electrolize&family=Shadows+Into+Light+Two&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
    body
{
background-color:#bcc20c;
font-family: "Bungee", sans-serif;
  font-weight: 400;
  font-style: normal;
}

.footer
{
background-color:#191f4f;
width:100%;
position:fixed;
color:white;
bottom:0px;
}

</style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <img src="{% static 'images/logo.jpg' %}" height="80px" width="120px">
    <a class="navbar-brand fw-bold fst-italic" href="#"><h2>ECOMMERCE</h2></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'shop:logout' %}">LOGOUT</a>
        </li>
          {% if user.is_superuser != True %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcategories' %}">HOME</a>
        </li>
                  <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"><sup>{{ count }}</sup></i></a>
        </li>
          <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            CATEGORIES
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
              {% endfor %}
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'shop:register' %}">REGISTER</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'shop:login' %}">LOGIN</a>
        </li>
              {% endif %}
        {% endif %}
          </ul>
        </li>
      </ul>
    </div>
      </ul>

      <form class="d-flex" method="POST" action="{% url 'search:searchproducts' %}">
          {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}

{% endblock %}
    <div class="footer">
    <h3><center>Copyright ©2024 All rights reserved</center></h3>
    </div>
</body>



</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mt-5" style="margin bottom:100px">
    <div class="row">
        <h3 class="text-center text-light">Shopping Cart</h3>
        <div class="col-8">
            <table class="table table-bordered table border-dark">
                <tr>
                    <th colspan="7">Cart Items</th>
                </tr>
                {% for i in cart %}
                <tr>
                    <td><img src="{{ i.product.image.url }}"height="150px" width="100px"></td>
                    <td>{{ i.product.name }}</td>
                    <td>Product ID:{{ i.product.id }}<br>
                        Quantity:{{ i.quantity }}<br>
                        Unit Price:{{ i.quantity }}*{{ i.prdouct.price }}</td>
                    <td>Subtotal:{{ i.subtotal }}</td>
                    <td>
                        {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa-solid fa-circle-plus me-2"></i></a>
                        <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa-solid fa-circle-minus me-2"></i></a>
                        <a href="{% url 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash-can me-2"></i></a>
                        {% else %}
                             <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa-solid fa-circle-minus me-2"></i></a>
                             <a href="{% url 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash-can me-2"></i></a>
                        {% endif %}
                    </td>
                     </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-4">
            <table class="table table-bordered">
                <tr>
                    <th colspan="4">Check Out</th>
                </tr>
                <tr>
                    <td colspan="4">Total Amount:{{ total }}</td>
                </tr>
            </table>
            <a class="btn btn-light" href="{% url 'cart:orderform' %}">Place Order</a>
            <a class="btn btn-primary" href="{% url 'shop:allcategories' %}" >Continue Shopping</a>
        </div>

    </div>
</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid mt-4" style="margin-bottom:30px">
    <img src="{% static 'images/banner_edit_1_1.jpg' %}" height="450px" width="100%">
</div>
<div class="container-fluid mt-1" style="margin-bottom:50px">
    <center><h2 style="margin-bottom:50px;">COLLECTIONS</h2></center>
    <p>the act of collecting. something that is collected; a group of objects or an amount of material accumulated in one location, especially for some purpose or as a result of some process: a stamp collection;a collection of unclaimed hats in the checkroom;a collection of books on Churchill.</p>
</div>
<div class="container-fluid" style="margin-bottom:50px">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-3">
            <div class="card" style="width: 18rem;">
  <img src="{{ i.image.url }}" height="300px" class="card-img-top" alt="...">
  <div class="card-body">
      <h5 class="card-title">{{ i.name }}</h5>
      <p class="card-text"></p>
    <a href="{% url 'shop:products' i.id %}" class="btn btn-primary">PRODUCTS</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-6">
    <div class="row">
        <div class="col-4 me-5">
    <img class="mt-2" src="{{ p.image.url }}" height="400px" width="400px">
        </div>
        <div class="col-6 me-5 mt-2 pt-3" style="padding-left:100px;">
         <h2>{{ p.name }}</h2>
         <p style="text-align:justify;line-height:1.8;">{{ p.desc }}</p>
         <h3>Price:{{ p.price }}</h3><br>
         <h5>Stock:{{ p.stock }}</h5><br><br>
            {% if user.is_superuser == True %}

            {% if p.stock > 0 %}
            <h3 class="text-dark">In Stock</h3>
            <a href="{url 'admin:index' %}" class="btn btn-primary mt-4" style="width:300px">Add Stock</a>
            {% else %}
            <h3 class="text-dark">Out of Stock</h3>
            <a href="{% url 'admin:index' %}" class="btn btn-primary mt-4" style="width:300px">Add Stock</a>
            {% endif %}

            {% else %}
            {% if p.stock > 0%}
         <a href="{% url 'cart:addtocart' p.id %}" class="btn btn-primary" style="width=300px;">Add to Cart</a>
            {% else%}
            <h3 class="text-light">Out of Stock</h3>
            {% endif %}

            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

ecommerce/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mt-4" style="margin-bottom:30px">
    <img src="{% static 'images/banner_edit_1_1.jpg' %}" height="450px" width="100%">
</div>

{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
LOGIN
{% endblock %}
{% block content %}
<h1 class="text-center">LOGIN...</h1>
<form method="POST">
{% csrf_token %}
<div class="mb-3">
    <label class="form-label">USER NAME</label>
    <input type="text" class="form-control" name="u">
  </div>
  <div class="mb-3">
    <label class="form-label">PASSWORD</label>
    <input type="password" class="form-control" name="p">
  </div>
<button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>{{ message }}</h3>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
    <label class="form-label">PHONE NO</label>
    <input type="number" class="form-control" name="ph">
  </div>
    <div class="mb-3">
    <label class="form-label">ADDRESS</label>
    <input type="text" class="form-control" name="ad">
  </div>
  <div class="mb-3">
    <label class="form-label">ACCNO</label>
    <input type="number" class="form-control" name="n">
  </div>
    <center>
    <button type="submit" class="btn btn-primary">Submit</button>
    </center>
</form>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3 style="color:black; margin-top:10px;">NAME OF THE CUSTOMER:{{user}}</h3></center>
{% for i in cart %}
<div class="container-fluid" style="width:1100px;">

    <div class="row border border-1 border-dark" >
        <div class="col-4 me-5 " style="margin-bottom:10px;">
    <img class="mt-2" src="{{i.product.image.url}}" height="300px" width="400px">
        </div>
        <div class="col-6 me-5 mt-2 pt-3" style="padding-left:100px;">
    <h4>PRODUCT NAME:{{i.product.name}}</h4>
    <h4>PRODUCT PRICE:{{i.product.price}}</h4>
    <h4>ADDRESS:{{i.address}}</h4>
    <h4>PHONE:{{i.phone}}</h4>
    <h4>NO OF ITEMS:{{i.no_of_item}}</h4>
    <h4>ORDERED ON:{{i.ordered_date}}</h4>
    <h4>DELIVERY STATUS:{{i.delivery_status}}</h4>
        </div>
    </div>
</div><br>
{% endfor %}
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid mt-4" style="margin-bottom:30px">
    <img src="{{ c.image.url }}" height="450px" width="100%">
</div>
<div class="container-fluid mt-1" style="margin-bottom:50px">
    <center><h2 style="margin-bottom:50px;">{{ c.name }}</h2></center>
    <p>{{ c.desc }}</p>
</div>
<div class="container-fluid" style="margin-bottom:50px">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-3">
            <div class="card" style="width: 18rem;">
  <img src="{{ i.image.url }}" height="300px" class="card-img-top" alt="...">
  <div class="card-body">
      <h5 class="card-title">{{ i.name }}</h5>

    <a href="{% url 'shop:detail' i.id %}" class="btn btn-primary">PRODUCTS</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
REGISTER
{% endblock %}
{% block content %}
<h1 class="text-center">REGISTER</h1>
<form method="POST"enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">USER NAME</label>
    <input type="text" class="form-control" name="u">
  </div>
  <div class="mb-3">
    <label class="form-label">PASSWORD</label>
    <input type="password" class="form-control" name="p">
  </div>
    <div class="mb-3">
    <label class="form-label">CONFIRM PASSWORD</label>
    <input type="password" class="form-control" name="c">
  </div>
  <div class="mb-3">
    <label class="form-label">E-MAIL</label>
    <input type="text" class="form-control" name="e">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

ecommerce/templates/searchproducts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="container-fluid mt-4">
        <h3 class="text-center">You have searched for<span class="text-light>"{{q}}</h3>
    </div>
</center>
<div class="container-fluid" style="margin-bottom:50px">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-3">
            <div class="card" style="width: 18rem;">
  <img src="{{ i.image.url }}" height="300px" class="card-img-top" alt="...">
  <div class="card-body">
      <h5 class="card-title">{{ i.name }}</h5>
      <p class="card-text"></p>
    <a href="{% url 'shop:detail' i.id %}" class="btn btn-primary">PRODUCTS</a>
  </div>
</div>
        </div>
        {% empty %}
        <h5 class="text-center text-danger">No result found </h5>
        {% endfor %}
    </div>
</div>
{% endblock %}